version: '3'

services:
  bar:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/bar/games/BAR.sdd:ro
      - ../../../../LuaUI/Widgets:/bar/LuaUI/Widgets:ro
      - ./testlog:/bar/testlog:rw
      - cache:/bar/cache:rw

volumes:
  cache:
